//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentResultManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public string UniversitySeatNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string Address { get; set; }
        public Nullable<long> ContactNumber { get; set; }
        public Nullable<long> OptionalContactNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    }
}
